### ISSUE TITLE
No backend interface displayed with smd_user_manager on txp 4.6.2

### ISSUE THREAD

**Issue by superjorge** [gocom/rah_change_passwords#1]
I’ve updated a site from Textpattern 4.5.7 to 4.6.2 using smd_user_manager and rah_change_passwords and now I can’t see the change user password interface when editing a single use profile.

Is it normal behaviour or should rah_change_passwords work under 4.6.2?

Thanks.

**Comment by gocom** [comment]
Fixed in 060e2b3

**Comment by superjorge** [comment]
Thanks!
